[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]

build-backend = "setuptools.build_meta"

[project]
name = "XX_pyproject"
version = "0.1.0"
description = "the package to test within a class"
authors = [
    { name = "Michael Bruneau"}, {name = "Emile Jacques"},
]"